package com.wikia.mwapi.enumtypes;

public enum PropEnum {
  CATEGORIES,
  CATEGORYINFO,
  CONTRIBUTORS,
  COORDINATES,
  DELETEDREVISIONS,
  DUPLICATEFILES,
  EXTLINKS,
  EXTRACTS,
  FILEUSAGE,
  FLAGGED,
  FLOWINFO,
  GLOBALUSAGE,
  IMAGEINFO,
  IMAGES,
  INFO,
  IWLINKS,
  LANGLINKS,
  LINKS,
  LINKSHERE,
  PAGEIMAGES,
  PAGEPROPS,
  PAGETERMS,
  REDIRECTS,
  REVISIONS,
  STASHIMAGEINFO,
  TEMPLATES,
  TRANSCLUDEDIN,
  TRANSCODESTATUS,
  VIDEOINFO;

  @Override
  public String toString() {
    return super.toString().toLowerCase();
  }
}
